#ifndef __TEST_ITEM_EXTERN_H__
#define __TEST_ITEM_EXTERN_H__

int test_lcd_start_extern(void);
int test_msensor_start_extern(void);
int test_key_start_extern(void);
int test_vibrator_start_extern(void);
int test_version_show_extern(void);
int test_phone_info_show_extern(void);
int test_cali_info_extern(void);
int test_vb_bl_start_extern(void);
int test_led_start_extern(void);
int test_tp_start_extern(void);
int test_multi_touch_start_extern(void);
int test_mainloopback_start_extern(void);
int test_assisloopback_start_extern(void);
int test_sdcard_start_extern(void);
int test_emmc_start_extern(void);
int test_rtc_start_extern(void);
int test_sdcard_pretest_extern(void);
int test_gsensor_start_extern(void);
int test_lsensor_start_extern(void);
int test_pxysensor_start_extern(void);
int test_psensor_start_extern(void);
int test_asensor_start_extern(void);
int cali_asensor_start_extern(void);
int cali_gsensor_start_extern(void);
int cali_msensor_start_extern(void);
int cali_lsensor_start_extern(void);
int cali_prosensor_start_extern(void);
int cali_auto_prosensor_start_extern(void);
int test_bcamera_start_extern(void);
int test_acamera_start_extern(void);
int test_flash_start_extern(void);
int test_facamera_start_extern(void);
int test_fcamera_start_extern(void);
int test_charge_start_extern(void);
int test_headset_start_extern(void);
int test_tel_start_extern(void);
int test_otg_start_extern(void);
int test_nfc_start_extern(void);
int test_fm_start_extern(void);
int test_bt_start_extern(void);
int test_bt_pretest_extern(void);
int test_wifi_start_extern(void);
int test_wifi_pretest_extern(void);
int test_gps_start_extern(void);
int test_flashlight_start_extern(void);
int test_gps_pretest_extern(void);
int test_sim_start_extern(void);
int test_sim_pretest_extern(void);
int test_receiver_start_extern(void);
int test_speaker_start_extern(void);
int test_soundtrigger_start_extern(void);
int test_fingersor_start_extern(void);

#endif /*__TEST_ITEM_H_*/
