#ifndef __TEST_ITEM_H__
#define __TEST_ITEM_H__

#include "chnmgr.h"
#include "at.h"
#include "testitem_common.h"
#include "testitem_extern.h"

int test_lcd_start(void);
int test_msensor_start(void);
int test_key_start(void);
int test_vibrator_start(void);
int test_version_show(void);
int test_phone_info_show(void);
int test_cali_info(void);
int test_vb_bl_start(void);
int test_led_start(void);
int test_tp_start(void);
int test_multi_touch_start(void);
int test_mainloopback_start(void);
int test_assisloopback_start(void);
int test_sdcard_start(void);
int test_emmc_start(void);
int test_rtc_start(void);
int test_sdcard_pretest(void);
int test_gsensor_start(void);
int test_lsensor_start(void);
int test_pxysensor_start(void);
int test_psensor_start(void);
int test_asensor_start(void);
int cali_asensor_start(void);
int cali_gsensor_start(void);
int cali_msensor_start(void);
int cali_lsensor_start(void);
int cali_prosensor_start(void);
int cali_auto_prosensor_start(void);
int test_bcamera_start(void);
int test_acamera_start(void);
int test_flash_start(void);
int test_facamera_start(void);
int test_fcamera_start(void);
int test_charge_start(void);
int test_headset_start(void);
int test_tel_start(void);
int test_otg_start(void);
int test_nfc_start(void);
int test_fm_start(void);
int test_bt_start(void);
int test_bt_pretest(void);
int test_wifi_start(void);
int test_wifi_pretest(void);
int test_gps_start(void);
int test_flashlight_start(void);
int test_gps_pretest(void);
int test_sim_start(void);
int test_sim_pretest(void);
int test_receiver_start(void);
int test_speaker_start(void);
int test_soundtrigger_start(void);
int test_fingersor_start(void);
int test_third_camera_start(void);

#endif /*__TEST_ITEM_H_*/
